services:
  payload:
    image: 339712886798.dkr.ecr.eu-central-1.amazonaws.com/websites/fart:latest
    ports:
      - '80:3000'
    volumes:
      # - .:/app
      - media:/app/media
      - node_modules:/app/node_modules
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: mongodb://mongo/default

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  media:
  node_modules:
