services:
  payload:
    build:
      dockerfile: Dockerfile
    # image: oven/bun
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "bun install && bun run build && bun run start"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: mongodb://mongo/fart

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
